# Generated by Django 6.0.1 on 2026-02-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=45, unique=True)),
                ('email_user', models.EmailField(max_length=6000, unique=True)),
                ('created_dat', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=6000)),
                ('salt_password', models.CharField(max_length=1000)),
                ('bio_user', models.CharField(max_length=3500)),
            ],
        ),
    ]
